### ISSUE TITLE
(intermediate value).globEager is not a function

### ISSUE THREAD

**Issue by towardsuffering** [robertguss/Astro-Theme-Creek#222]
I am getting this error with 'astro build'.
(intermediate value).globEager is not a function
  Stack trace:
    at file:///home/carot/Astro-Theme-Creek/dist/chunks/pages/rss_jtdt-a9R.mjs:3:38
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async generatePages (file:///home/carot/.nvm/versions/node/v20.4.0/lib/node_modules/astro/dist/core/build/generate.js:156:9)
    at async AstroBuilder.build (file:///home/carot/.nvm/versions/node/v20.4.0/lib/node_modules/astro/dist/core/build/index.js:138:5)
    at async build (file:///home/carot/.nvm/versions/node/v20.4.0/lib/node_modules/astro/dist/core/build/index.js:47:3)

**Comment by manuelsanchez2** [comment]
Same here!
