### ISSUE TITLE
error   Expected ";" but found ":" in MDX

### ISSUE THREAD

**Issue by peterroe** [robertguss/Astro-Theme-Creek#55]
**Stack:**
	
```shell
 error   Expected ";" but found ":"
  File:
    /Users/lsh/Desktop/t/packages/Astro-Theme-Creek/src/pages/posts/first.mdx:2:6
  Stacktrace:
Error: Transform failed with 1 error:
/Users/lsh/Desktop/t/packages/Astro-Theme-Creek/src/pages/posts/first.mdx:2:6: ERROR: Expected ";" but found ":"
    at failureErrorWithLog (/Users/lsh/Desktop/t/packages/Astro-Theme-Creek/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/lsh/Desktop/t/packages/Astro-Theme-Creek/node_modules/esbuild/lib/main.js:1413:29
    at /Users/lsh/Desktop/t/packages/Astro-Theme-Creek/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/lsh/Desktop/t/packages/Astro-Theme-Creek/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/lsh/Desktop/t/packages/Astro-Theme-Creek/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
```

**Minimum steps to reproduce：**

1. Rename `installing-go-on-a-mac.md` to `installing-go-on-a-mac.mdx`:

```diff
posts
-	installing-go-on-a-mac.md
+	installing-go-on-a-mac.mdx
```

2. Update index.astro:

```diff
- const allPosts = await Astro.glob<MarkdownFrontmatter>('./posts/*.md');
+ const allPosts = await Astro.glob<MarkdownFrontmatter>('./posts/*.{md,mdx}');
```

I try to fix it, but i am fail :(

**Comment by robertguss** [comment]
@peterroe This theme is not setup to use mdx. You will need to properly set it up and also use React as MDX is react components in markdown files.

**Comment by saisantosh-revvity** [comment]
I installed mdx extension and modified the config. but still have the same issue
